export const MENU_MASTER = {
  dashboard: {
    id: 1,
    key: 'dashboard',
    label: 'Dashboard',
    path: '/',
    icon: 'LayoutDashboard',
  },
  monitor: {
    id: 2,
    key: 'monitor',
    label: 'Monitor',
    path: '/monitor',
    icon: 'Monitor',
  },
  users: {
    id: 3,
    key: 'users',
    label: 'Users',
    path: '/users',
    icon: 'Users',
  },
  settings: {
    id: 4,
    key: 'settings',
    label: 'Settings',
    path: '/settings',
    icon: 'Settings',
    children: [
      {
        id: 41,
        key: 'client',
        label: 'Client',
        path: '/settings/client',
        icon: 'Building2',
      },
      {
        id: 42,
        key: 'employee',
        label: 'Employee',
        path: '/settings/employee',
        icon: 'UserCog',
      },
    ],
  },
  passwords: {
    id: 5,
    key: 'passwords',
    label: 'Passwords',
    path: '/passwords',
    icon: 'RectangleEllipsis',
    children: [
      {
        id: 51,
        key: 'passwordmanager',
        label: 'Password Manager',
        path: '/passwords/password-manager',
        icon: 'KeyRound',
      },
      {
        id: 52,
        key: 'logs',
        label: 'Logs',
        path: '/passwords/logs',
        icon: 'Logs',
      },
    ],
  },
  masters: {
    id: 6,
    key: 'masters',
    label: 'Masters',
    path: '/masters',
    icon: 'SquareAsterisk',
    children: [
      {
        id: 61,
        key: 'tags',
        label: 'Tags',
        path: '/masters/tags',
        icon: 'Tags',
      },
      {
        id: 62,
        key: 'role',
        label: 'Roles',
        path: '/masters/roles',
        icon: 'UserRoundKey',
      },
      {
        id: 63,
        key: 'department',
        label: 'Department',
        path: '/masters/department',
        icon: 'Building2',
      },
      {
        id: 64,
        key: 'group',
        label: 'Group',
        path: '/masters/group',
        icon: 'Boxes',
      },
    ],
  },
};
